<a href="https://colab.research.google.com/github/sridharshini2004-boopathy/data_analytics_project/blob/main/Project3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
import pandas as pd
df=pd.read_csv("/content/breast_cancer_dataset.csv")

In [ ]:
!pip install pandas
!pip install numpy

In [ ]:
!pip install matplotlib
!pip install seaborn

In [ ]:
!pip install scikit-learn

In [ ]:
import pandas as pd
df=pd.read_csv("/content/breast_cancer_dataset.csv")
df

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000     70.0    2.707  0.467409   8.8071     9.702400   
1     83  20.690495     92.0    3.115  0.706897   8.8438     5.429285   
2     82  23.124670     91.0    4.498  1.009651  17.9393    22.432040   
3     68  21.367521     77.0    3.226  0.612725   9.8827     7.169560   
4     86  21.111111     92.0    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000     92.0    3.330  0.755688  54.6800    12.100000   
112   62  26.840000    100.0    4.530  1.117400  12.4500    21.420000   
113   65  32.050000     97.0    5.730  1.370998  61.4800    22.540000   
114   72  25.590000     82.0    2.820  0.570392  24.9600    33.750000   
115   86  27.180000    138.0   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               0  
1     4.06405  468.786               0  
2     9.27715  554.697               0  
3    12.76600  928.220               0  
4    10.57635  773.920               0  
..        ...      ...             ...  
111  10.96000  268.230               1  
112   7.32000  330.160               1  
113  10.33000  314.050               1  
114   3.27000  392.460               1  
115   4.35000   90.090               1  

[116 rows x 10 columns]

In [ ]:
df.head(15)

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0    48  23.500000     70.0    2.707  0.467409   8.8071     9.702400   
1    83  20.690495     92.0    3.115  0.706897   8.8438     5.429285   
2    82  23.124670     91.0    4.498  1.009651  17.9393    22.432040   
3    68  21.367521     77.0    3.226  0.612725   9.8827     7.169560   
4    86  21.111111     92.0    3.549  0.805386   6.6994     4.819240   
5    49  22.854458     92.0    3.226  0.732087   6.8317    13.679750   
6    89  22.700000      NaN    4.690  0.890787   6.9640     5.589865   
7    76  23.800000    118.0    6.470  1.883201   4.3110    13.251320   
8    73  22.000000     97.0    3.350  0.801543      NaN    10.358725   
9    75  23.000000     83.0    4.952  1.013839  17.1270    11.578990   
10   34  21.470000     78.0    3.469  0.667436  14.5700    13.110000   
11   29  23.010000     82.0    5.663  1.145436  35.5900    26.720000   
12   25  22.860000     82.0    4.090  0.827271  20.4500    23.670000   
13   24  18.670000     88.0      NaN  1.330000   8.8800    36.060000   
14   38  23.340000     75.0    5.782  1.069670  15.2600    17.950000   

    Resistin     MCP.1  Classification  
0    7.99585   417.114               0  
1    4.06405   468.786               0  
2    9.27715   554.697               0  
3   12.76600   928.220               0  
4   10.57635   773.920               0  
5   10.31760   530.410               0  
6   12.93610  1256.083               0  
7    5.10420   280.694               0  
8    6.28445   136.855               0  
9    7.09130   318.302               0  
10   6.92000   354.600               0  
11   4.58000   174.800               0  
12   5.14000   313.730               0  
13   6.85000   632.220               0  
14   9.35000   165.020               0

In [ ]:
df.tail(7)

Age    BMI  Glucose  Insulin      HOMA  Leptin  Adiponectin  Resistin  \
109   75  30.48    152.0     7.01  2.628283   50.53        10.06     11.73   
110   54  36.05    119.0    11.91  3.495982   89.27         8.01      5.06   
111   45  26.85     92.0     3.33  0.755688   54.68        12.10     10.96   
112   62  26.84    100.0     4.53  1.117400   12.45        21.42      7.32   
113   65  32.05     97.0     5.73  1.370998   61.48        22.54     10.33   
114   72  25.59     82.0     2.82  0.570392   24.96        33.75      3.27   
115   86  27.18    138.0    19.91  6.777364   90.28        14.11      4.35   

      MCP.1  Classification  
109   99.45               1  
110  218.28               1  
111  268.23               1  
112  330.16               1  
113  314.05               1  
114  392.46               1  
115   90.09               1

In [ ]:
df.isnull().sum().sum()

np.int64(17)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             116 non-null    int64  
 1   BMI             116 non-null    float64
 2   Glucose         111 non-null    float64
 3   Insulin         112 non-null    float64
 4   HOMA            116 non-null    float64
 5   Leptin          113 non-null    float64
 6   Adiponectin     112 non-null    float64
 7   Resistin        115 non-null    float64
 8   MCP.1           116 non-null    float64
 9   Classification  116 non-null    int64  
dtypes: float64(8), int64(2)
memory usage: 9.2 KB


In [ ]:
df.isnull().sum()

Age               0
BMI               0
Glucose           5
Insulin           4
HOMA              0
Leptin            3
Adiponectin       4
Resistin          1
MCP.1             0
Classification    0
dtype: int64

In [ ]:
df['Glucose']=df['Glucose'].fillna(df['Glucose'].median())
df['Insulin']=df['Insulin'].fillna(df['Insulin'].median())
df['Leptin']=df['Leptin'].fillna(df['Leptin'].median())
df['Adiponectin']=df['Adiponectin'].fillna(df['Adiponectin'].median())
df['Resistin']=df['Resistin'].fillna(df['Resistin'].median())

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
x=df.drop(["Classification"],axis=1)


y=df["Classification"]
x

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000     70.0    2.707  0.467409   8.8071     9.702400   
1     83  20.690495     92.0    3.115  0.706897   8.8438     5.429285   
2     82  23.124670     91.0    4.498  1.009651  17.9393    22.432040   
3     68  21.367521     77.0    3.226  0.612725   9.8827     7.169560   
4     86  21.111111     92.0    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000     92.0    3.330  0.755688  54.6800    12.100000   
112   62  26.840000    100.0    4.530  1.117400  12.4500    21.420000   
113   65  32.050000     97.0    5.730  1.370998  61.4800    22.540000   
114   72  25.590000     82.0    2.820  0.570392  24.9600    33.750000   
115   86  27.180000    138.0   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  
0     7.99585  417.114  
1     4.06405  468.786  
2     9.27715  554.697  
3    12.76600  928.220  
4    10.57635  773.920  
..        ...      ...  
111  10.96000  268.230  
112   7.32000  330.160  
113  10.33000  314.050  
114   3.27000  392.460  
115   4.35000   90.090  

[116 rows x 9 columns]

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
111    1
112    1
113    1
114    1
115    1
Name: Classification, Length: 116, dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x=sc.fit_transform(x)
print(x)


[[3.69230769e-01 2.53850329e-01 7.09219858e-02 ... 2.21151727e-01
  6.06648498e-02 2.24659127e-01]
 [9.07692308e-01 1.14826180e-01 2.26950355e-01 ... 1.03706769e-01
  1.08258334e-02 2.55926278e-01]
 [8.92307692e-01 2.35277707e-01 2.19858156e-01 ... 5.71021092e-01
  7.69064520e-02 3.07911729e-01]
 ...
 [6.30769231e-01 6.76934210e-01 2.62411348e-01 ... 5.73988332e-01
  9.02522500e-02 1.62294256e-01]
 [7.38461538e-01 3.57270833e-01 1.56028369e-01 ... 8.82090964e-01
  7.60552668e-04 2.09740790e-01]
 [9.53846154e-01 4.35949590e-01 5.53191489e-01 ... 3.42292954e-01
  1.44505007e-02 2.67742226e-02]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(92, 9)
(24, 9)
(92,)
(24,)


Logistic Regression


In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7083333333333334
[[ 7  5]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.78      0.58      0.67        12
           1       0.67      0.83      0.74        12

    accuracy                           0.71        24
   macro avg       0.72      0.71      0.70        24
weighted avg       0.72      0.71      0.70        24



In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #underfit

0.75
[[11  1]
 [ 5  7]]
              precision    recall  f1-score   support

           0       0.69      0.92      0.79        12
           1       0.88      0.58      0.70        12

    accuracy                           0.75        24
   macro avg       0.78      0.75      0.74        24
weighted avg       0.78      0.75      0.74        24



Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6666666666666666
[[ 6  6]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.75      0.50      0.60        12
           1       0.62      0.83      0.71        12

    accuracy                           0.67        24
   macro avg       0.69      0.67      0.66        24
weighted avg       0.69      0.67      0.66        24



In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_test,y_test)
y_pred=dt.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #underfit

1.0
[[12  0]
 [ 0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        12

    accuracy                           1.00        24
   macro avg       1.00      1.00      1.00        24
weighted avg       1.00      1.00      1.00        24



In [ ]:
dc=DecisionTreeClassifier()
dc.fit(x_train,y_train)
y_pred=dc.predict(x_test)
print(y_pred)

[1 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 1 1 0 1 1 1 1 0]


In [ ]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.6666666666666666


In [ ]:
dc=DecisionTreeClassifier()
dc.fit(x_test,y_test)
y_pred=dc.predict(x_test)
print(y_pred)

[1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0]


In [ ]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

1.0


In [ ]:
dc=DecisionTreeClassifier(random_state=42,criterion='gini',max_depth=9,min_samples_split=21,max_leaf_nodes=8,splitter='best')
dc.fit(x_train,y_train)
y_pred=dc.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.75


In [ ]:
dc=DecisionTreeClassifier(random_state=42,criterion='gini',max_depth=8,min_samples_split=20,splitter='best', max_leaf_nodes=8,min_impurity_decrease=0.3,max_features=90)
dc.fit(x_test,y_test)
y_pred=dc.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.5


Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7916666666666666
[[10  2]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.77      0.83      0.80        12
           1       0.82      0.75      0.78        12

    accuracy                           0.79        24
   macro avg       0.79      0.79      0.79        24
weighted avg       0.79      0.79      0.79        24



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_test,y_test)
y_pred=rf.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #underfit

1.0
[[12  0]
 [ 0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        12

    accuracy                           1.00        24
   macro avg       1.00      1.00      1.00        24
weighted avg       1.00      1.00      1.00        24



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=700,max_depth=10,min_samples_leaf=10,max_features=1.0,bootstrap=True)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9166666666666666
[[11  1]
 [ 1 11]]
              precision    recall  f1-score   support

           0       0.92      0.92      0.92        12
           1       0.92      0.92      0.92        12

    accuracy                           0.92        24
   macro avg       0.92      0.92      0.92        24
weighted avg       0.92      0.92      0.92        24



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=500,max_depth=7,min_samples_leaf=8,max_features=1.0,bootstrap=True)
rf.fit(x_test,y_test)
y_pred=rf.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7916666666666666
[[10  2]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.77      0.83      0.80        12
           1       0.82      0.75      0.78        12

    accuracy                           0.79        24
   macro avg       0.79      0.79      0.79        24
weighted avg       0.79      0.79      0.79        24



Hyper Parameter Tuning


In [ ]:
import xgboost as xgb
model=xgb.XGBClassifier(n_estimator=0)

model.fit(x_train,y_train)
y_pred=model.predict(x_test)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [10:27:03] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


In [ ]:
accuracy_score(y_test,y_pred)
confusion_matrix(y_test,y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        12
           1       0.92      0.92      0.92        12

    accuracy                           0.92        24
   macro avg       0.92      0.92      0.92        24
weighted avg       0.92      0.92      0.92        24



In [ ]:
model.fit(x_test,y_test)
y_pred=model.predict(x_test)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [10:27:48] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


In [ ]:
accuracy_score(y_test,y_pred)
confusion_matrix(y_test,y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        12

    accuracy                           1.00        24
   macro avg       1.00      1.00      1.00        24
weighted avg       1.00      1.00      1.00        24



In [ ]:
rf_param={
    'n_estimators':[20,30,40,50,60,70,80,90,100,110,120],
    'max_depth':[2,3,4,5,6,7,8,9,10,11],
    'min_samples_split':[2,3,4,5,6,7,8,9,10,11],
    'min_samples_leaf':[1,2,3,4,5,6,7,8,9,10,11]
}
from sklearn.model_selection import RandomizedSearchCV
rf_model=RandomForestClassifier()
rf_cv=RandomizedSearchCV(rf_model,rf_param,cv=5)
rf_cv.fit(x_train,y_train)
rf_cv.best_params_

{'n_estimators': 40,
 'min_samples_split': 2,
 'min_samples_leaf': 4,
 'max_depth': 9}

In [ ]:
rf_param={
    'n_estimators':[10,20,30,40,50,60,70,80,90,100],
    'max_depth':[1,2,3,4,5,6,7,8,9,10],
    'min_samples_split':[2,3,4,5,6,7,8,9,10],
    'min_samples_leaf':[1,2,3,4,5,6,7,8,9,10]
}
from sklearn.model_selection import RandomizedSearchCV
rf_model=RandomForestClassifier()
rf_cv=RandomizedSearchCV(rf_model,rf_param,cv=5)
rf_cv.fit(x_test,y_test)
rf_cv.best_params_

{'n_estimators': 30,
 'min_samples_split': 9,
 'min_samples_leaf': 1,
 'max_depth': 9}

In [ ]:
rf_model=RandomForestClassifier(n_estimators=40,min_samples_split=2,min_samples_leaf=4,max_depth=9)
model=rf_model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)
confusion_matrix(y_test,y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       1.00      0.92      0.96        12

    accuracy                           0.96        24
   macro avg       0.96      0.96      0.96        24
weighted avg       0.96      0.96      0.96        24



In [ ]:
rf_model=RandomForestClassifier(n_estimators=30,min_samples_split=9,min_samples_leaf=1,max_depth=9)
model=rf_model.fit(x_test,y_test)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)
confusion_matrix(y_test,y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        12
           1       0.92      1.00      0.96        12

    accuracy                           0.96        24
   macro avg       0.96      0.96      0.96        24
weighted avg       0.96      0.96      0.96        24




K Neighbors Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7916666666666666
[[10  2]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.77      0.83      0.80        12
           1       0.82      0.75      0.78        12

    accuracy                           0.79        24
   macro avg       0.79      0.79      0.79        24
weighted avg       0.79      0.79      0.79        24



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_test,y_test)
y_pred=knn.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #underfit

0.875
[[11  1]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.85      0.92      0.88        12
           1       0.91      0.83      0.87        12

    accuracy                           0.88        24
   macro avg       0.88      0.88      0.87        24
weighted avg       0.88      0.88      0.87        24



SVC

In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8333333333333334
[[10  2]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        12
           1       0.83      0.83      0.83        12

    accuracy                           0.83        24
   macro avg       0.83      0.83      0.83        24
weighted avg       0.83      0.83      0.83        24



In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_test,y_test)
y_pred=svc.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #underfit

0.9166666666666666
[[12  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.92        12
           1       1.00      0.83      0.91        12

    accuracy                           0.92        24
   macro avg       0.93      0.92      0.92        24
weighted avg       0.93      0.92      0.92        24



Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.75
[[11  1]
 [ 5  7]]
              precision    recall  f1-score   support

           0       0.69      0.92      0.79        12
           1       0.88      0.58      0.70        12

    accuracy                           0.75        24
   macro avg       0.78      0.75      0.74        24
weighted avg       0.78      0.75      0.74        24



In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #underfit

0.875
[[11  1]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.85      0.92      0.88        12
           1       0.91      0.83      0.87        12

    accuracy                           0.88        24
   macro avg       0.88      0.88      0.87        24
weighted avg       0.88      0.88      0.87        24



Decision Tree Parametric
