In [1]:
!pip install pandas
!pip install numpy


In [2]:
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn


In [3]:
import pandas as pd
df=pd.read_csv("/content/Weather Test Data.csv")


In [4]:
df


row ID Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0          Row0   Albury     12.9     25.7       0.0          NaN       NaN   
1          Row1   Albury      9.2     28.0       0.0          NaN       NaN   
2          Row2   Albury     14.3     25.0       0.0          NaN       NaN   
3          Row3   Albury      9.7     31.9       0.0          NaN       NaN   
4          Row4   Albury     15.9     18.6      15.6          NaN       NaN   
...         ...      ...      ...      ...       ...          ...       ...   
42673  Row43634    Uluru      2.3     21.4       0.0          NaN       NaN   
42674  Row43635    Uluru      2.6     22.5       0.0          NaN       NaN   
42675  Row43636    Uluru      7.4     20.6       0.0          NaN       NaN   
42676  Row43637    Uluru      7.8     27.0       0.0          NaN       NaN   
42677    Row128   Albury     13.5     23.1       3.2          NaN       NaN   

      WindGustDir  WindGustSpeed WindDir9am  ... WindSpeed3pm  Humidity9am  \
0             WSW           46.0          W  ...         26.0         38.0   
1              NE           24.0         SE  ...          9.0         45.0   
2               W           50.0         SW  ...         24.0         49.0   
3             NNW           80.0         SE  ...         28.0         42.0   
4               W           61.0        NNW  ...         28.0         76.0   
...           ...            ...        ...  ...          ...          ...   
42673          SE           22.0         SE  ...          7.0         60.0   
42674           S           19.0          S  ...          7.0         59.0   
42675           E           35.0        ESE  ...         17.0         63.0   
42676          SE           28.0        SSE  ...          7.0         51.0   
42677          NW           46.0        WNW  ...         20.0         84.0   

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0             30.0       1007.6       1008.7       NaN       2.0     21.0   
1             16.0       1017.6       1012.8       NaN       NaN     18.1   
2             19.0       1009.6       1008.2       1.0       NaN     18.1   
3              9.0       1008.9       1003.6       NaN       NaN     18.3   
4             93.0        994.3        993.0       8.0       8.0     17.4   
...            ...          ...          ...       ...       ...      ...   
42673         28.0       1026.9       1022.8       NaN       NaN      8.9   
42674         24.0       1025.0       1021.4       NaN       NaN      8.8   
42675         33.0       1027.2       1023.3       NaN       NaN     11.0   
42676         24.0       1019.4       1016.5       3.0       2.0     15.1   
42677         53.0       1016.7       1015.3       1.0       1.0     17.5   

       Temp3pm  RainToday  
0         23.2         No  
1         26.5         No  
2         24.6         No  
3         30.2         No  
4         15.8        Yes  
...        ...        ...  
42673     20.3         No  
42674     22.1         No  
42675     20.3         No  
42676     26.0         No  
42677     23.0        Yes  

[42678 rows x 22 columns]

In [5]:
df.head(10)


row ID Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0   Row0   Albury     12.9     25.7       0.0          NaN       NaN   
1   Row1   Albury      9.2     28.0       0.0          NaN       NaN   
2   Row2   Albury     14.3     25.0       0.0          NaN       NaN   
3   Row3   Albury      9.7     31.9       0.0          NaN       NaN   
4   Row4   Albury     15.9     18.6      15.6          NaN       NaN   
5   Row6   Albury     11.5     29.3       0.0          NaN       NaN   
6   Row7   Albury     16.2     33.9       0.0          NaN       NaN   
7   Row8   Albury     12.0     24.4       0.8          NaN       NaN   
8   Row9   Albury     11.3     26.5       0.0          NaN       NaN   
9  Row10   Albury     12.9     35.8       0.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... WindSpeed3pm  Humidity9am  \
0         WSW           46.0          W  ...         26.0         38.0   
1          NE           24.0         SE  ...          9.0         45.0   
2           W           50.0         SW  ...         24.0         49.0   
3         NNW           80.0         SE  ...         28.0         42.0   
4           W           61.0        NNW  ...         28.0         76.0   
5           S           24.0         SE  ...          9.0         56.0   
6         WSW           35.0         SE  ...         13.0         45.0   
7           W           39.0        WNW  ...         17.0         48.0   
8         WNW           56.0          W  ...         31.0         46.0   
9         WNW           41.0        ENE  ...         26.0         41.0   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0         30.0       1007.6       1008.7       NaN       2.0     21.0   
1         16.0       1017.6       1012.8       NaN       NaN     18.1   
2         19.0       1009.6       1008.2       1.0       NaN     18.1   
3          9.0       1008.9       1003.6       NaN       NaN     18.3   
4         93.0        994.3        993.0       8.0       8.0     17.4   
5         28.0       1019.3       1014.8       NaN       NaN     19.1   
6         19.0       1010.9       1007.6       NaN       1.0     23.2   
7         28.0       1006.1       1005.1       1.0       NaN     16.9   
8         26.0       1004.5       1003.2       NaN       NaN     19.7   
9          9.0       1012.6       1009.2       NaN       NaN     22.4   

   Temp3pm  RainToday  
0     23.2         No  
1     26.5         No  
2     24.6         No  
3     30.2         No  
4     15.8        Yes  
5     27.3         No  
6     33.0         No  
7     22.7         No  
8     25.7         No  
9     34.4         No  

[10 rows x 22 columns]

In [6]:
df.tail(5)

row ID Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
42673  Row43634    Uluru      2.3     21.4       0.0          NaN       NaN   
42674  Row43635    Uluru      2.6     22.5       0.0          NaN       NaN   
42675  Row43636    Uluru      7.4     20.6       0.0          NaN       NaN   
42676  Row43637    Uluru      7.8     27.0       0.0          NaN       NaN   
42677    Row128   Albury     13.5     23.1       3.2          NaN       NaN   

      WindGustDir  WindGustSpeed WindDir9am  ... WindSpeed3pm  Humidity9am  \
42673          SE           22.0         SE  ...          7.0         60.0   
42674           S           19.0          S  ...          7.0         59.0   
42675           E           35.0        ESE  ...         17.0         63.0   
42676          SE           28.0        SSE  ...          7.0         51.0   
42677          NW           46.0        WNW  ...         20.0         84.0   

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
42673         28.0       1026.9       1022.8       NaN       NaN      8.9   
42674         24.0       1025.0       1021.4       NaN       NaN      8.8   
42675         33.0       1027.2       1023.3       NaN       NaN     11.0   
42676         24.0       1019.4       1016.5       3.0       2.0     15.1   
42677         53.0       1016.7       1015.3       1.0       1.0     17.5   

       Temp3pm  RainToday  
42673     20.3         No  
42674     22.1         No  
42675     20.3         No  
42676     26.0         No  
42677     23.0        Yes  

[5 rows x 22 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42678 entries, 0 to 42677
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42678 non-null  object 
 1   Location       42678 non-null  object 
 2   MinTemp        42484 non-null  float64
 3   MaxTemp        42586 non-null  float64
 4   Rainfall       42251 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    39869 non-null  object 
 8   WindGustSpeed  39888 non-null  float64
 9   WindDir9am     39671 non-null  object 
 10  WindDir3pm     41548 non-null  object 
 11  WindSpeed9am   42265 non-null  float64
 12  WindSpeed3pm   41883 non-null  float64
 13  Humidity9am    42137 non-null  float64
 14  Humidity3pm    41574 non-null  float64
 15  Pressure9am    38412 non-null  float64
 16  Pressure3pm    38433 non-null  float64
 17  Cloud9am       26593 non-null  float64
 18  Cloud3

In [8]:
df.shape

(42678, 22)

In [9]:
df['Location'].head(10)


0    Albury
1    Albury
2    Albury
3    Albury
4    Albury
5    Albury
6    Albury
7    Albury
8    Albury
9    Albury
Name: Location, dtype: object

In [10]:
df[['MinTemp','MaxTemp','Rainfall']].tail(7)

MinTemp  MaxTemp  Rainfall
42671      1.5     19.2       0.0
42672      2.4     19.1       0.0
42673      2.3     21.4       0.0
42674      2.6     22.5       0.0
42675      7.4     20.6       0.0
42676      7.8     27.0       0.0
42677     13.5     23.1       3.2

In [11]:
df.isnull()


row ID  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0       False     False    False    False     False         True      True   
1       False     False    False    False     False         True      True   
2       False     False    False    False     False         True      True   
3       False     False    False    False     False         True      True   
4       False     False    False    False     False         True      True   
...       ...       ...      ...      ...       ...          ...       ...   
42673   False     False    False    False     False         True      True   
42674   False     False    False    False     False         True      True   
42675   False     False    False    False     False         True      True   
42676   False     False    False    False     False         True      True   
42677   False     False    False    False     False         True      True   

       WindGustDir  WindGustSpeed  WindDir9am  ...  WindSpeed3pm  Humidity9am  \
0            False          False       False  ...         False        False   
1            False          False       False  ...         False        False   
2            False          False       False  ...         False        False   
3            False          False       False  ...         False        False   
4            False          False       False  ...         False        False   
...            ...            ...         ...  ...           ...          ...   
42673        False          False       False  ...         False        False   
42674        False          False       False  ...         False        False   
42675        False          False       False  ...         False        False   
42676        False          False       False  ...         False        False   
42677        False          False       False  ...         False        False   

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0            False        False        False      True     False    False   
1            False        False        False      True      True    False   
2            False        False        False     False      True    False   
3            False        False        False      True      True    False   
4            False        False        False     False     False    False   
...            ...          ...          ...       ...       ...      ...   
42673        False        False        False      True      True    False   
42674        False        False        False      True      True    False   
42675        False        False        False      True      True    False   
42676        False        False        False     False     False    False   
42677        False        False        False     False     False    False   

       Temp3pm  RainToday  
0        False      False  
1        False      False  
2        False      False  
3        False      False  
4        False      False  
...        ...        ...  
42673    False      False  
42674    False      False  
42675    False      False  
42676    False      False  
42677    False      False  

[42678 rows x 22 columns]

In [12]:
df.isnull().sum()

row ID               0
Location             0
MinTemp            194
MaxTemp             92
Rainfall           427
Evaporation      18313
Sunshine         20500
WindGustDir       2809
WindGustSpeed     2790
WindDir9am        3007
WindDir3pm        1130
WindSpeed9am       413
WindSpeed3pm       795
Humidity9am        541
Humidity3pm       1104
Pressure9am       4266
Pressure3pm       4245
Cloud9am         16085
Cloud3pm         17092
Temp9am            290
Temp3pm            822
RainToday          427
dtype: int64

In [13]:
df.isnull().sum().sum()


np.int64(95342)

In [14]:
df.duplicated().sum()

np.int64(1)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['WindGustDir']=le.fit_transform(df['WindGustDir'])
df['WindGustDir'].info()
df.info()


<class 'pandas.core.series.Series'>
Index: 42677 entries, 0 to 42676
Series name: WindGustDir
Non-Null Count  Dtype
--------------  -----
42677 non-null  int64
dtypes: int64(1)
memory usage: 666.8 KB
<class 'pandas.core.frame.DataFrame'>
Index: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  object 
 1   Location       42677 non-null  object 
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object 
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['row ID']=le.fit_transform(df['row ID'])
df['row ID'].info()
df.info()

<class 'pandas.core.series.Series'>
Index: 42677 entries, 0 to 42676
Series name: row ID
Non-Null Count  Dtype
--------------  -----
42677 non-null  int64
dtypes: int64(1)
memory usage: 666.8 KB
<class 'pandas.core.frame.DataFrame'>
Index: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  object 
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object 
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Location']=le.fit_transform(df['Location'])
df['Location'].info()
df.info()

<class 'pandas.core.series.Series'>
Index: 42677 entries, 0 to 42676
Series name: Location
Non-Null Count  Dtype
--------------  -----
42677 non-null  int64
dtypes: int64(1)
memory usage: 666.8 KB
<class 'pandas.core.frame.DataFrame'>
Index: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object 
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  flo

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['WindDir9am']=le.fit_transform(df['WindDir9am'])
df['WindDir9am'].info()
df.info()

<class 'pandas.core.series.Series'>
Index: 42677 entries, 0 to 42676
Series name: WindDir9am
Non-Null Count  Dtype
--------------  -----
42677 non-null  int64
dtypes: int64(1)
memory usage: 666.8 KB
<class 'pandas.core.frame.DataFrame'>
Index: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     42677 non-null  int64  
 10  WindDir3pm     41547 non-null  object 
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  f

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['WindDir3pm']=le.fit_transform(df['WindDir3pm'])
df['WindDir3pm'].info()
df.info()

<class 'pandas.core.series.Series'>
Index: 42677 entries, 0 to 42676
Series name: WindDir3pm
Non-Null Count  Dtype
--------------  -----
42677 non-null  int64
dtypes: int64(1)
memory usage: 666.8 KB
<class 'pandas.core.frame.DataFrame'>
Index: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     42677 non-null  int64  
 10  WindDir3pm     42677 non-null  int64  
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  f

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['RainToday']=le.fit_transform(df['RainToday'])
df['RainToday'].info()
df.info()

<class 'pandas.core.series.Series'>
Index: 42677 entries, 0 to 42676
Series name: RainToday
Non-Null Count  Dtype
--------------  -----
42677 non-null  int64
dtypes: int64(1)
memory usage: 666.8 KB
<class 'pandas.core.frame.DataFrame'>
Index: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     42677 non-null  int64  
 10  WindDir3pm     42677 non-null  int64  
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  fl

In [23]:
df.info()


<class 'pandas.core.frame.DataFrame'>
Index: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   row ID         42677 non-null  int64  
 1   Location       42677 non-null  int64  
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    42677 non-null  int64  
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     42677 non-null  int64  
 10  WindDir3pm     42677 non-null  int64  
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3pm   

In [24]:
df.head()

row ID  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0       0         2     12.9     25.7       0.0          NaN       NaN   
1       1         2      9.2     28.0       0.0          NaN       NaN   
2   10859         2     14.3     25.0       0.0          NaN       NaN   
3   21632         2      9.7     31.9       0.0          NaN       NaN   
4   32544         2     15.9     18.6      15.6          NaN       NaN   

   WindGustDir  WindGustSpeed  WindDir9am  ...  WindSpeed3pm  Humidity9am  \
0           15           46.0          13  ...          26.0         38.0   
1            4           24.0           9  ...           9.0         45.0   
2           13           50.0          12  ...          24.0         49.0   
3            6           80.0           9  ...          28.0         42.0   
4           13           61.0           6  ...          28.0         76.0   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0         30.0       1007.6       1008.7       NaN       2.0     21.0   
1         16.0       1017.6       1012.8       NaN       NaN     18.1   
2         19.0       1009.6       1008.2       1.0       NaN     18.1   
3          9.0       1008.9       1003.6       NaN       NaN     18.3   
4         93.0        994.3        993.0       8.0       8.0     17.4   

   Temp3pm  RainToday  
0     23.2          0  
1     26.5          0  
2     24.6          0  
3     30.2          0  
4     15.8          1  

[5 rows x 22 columns]

In [25]:
df['MinTemp']=df['MinTemp'].fillna(df['MinTemp'].median())

In [26]:
df.head()

row ID  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0       0         2     12.9     25.7       0.0          NaN       NaN   
1       1         2      9.2     28.0       0.0          NaN       NaN   
2   10859         2     14.3     25.0       0.0          NaN       NaN   
3   21632         2      9.7     31.9       0.0          NaN       NaN   
4   32544         2     15.9     18.6      15.6          NaN       NaN   

   WindGustDir  WindGustSpeed  WindDir9am  ...  WindSpeed3pm  Humidity9am  \
0           15           46.0          13  ...          26.0         38.0   
1            4           24.0           9  ...           9.0         45.0   
2           13           50.0          12  ...          24.0         49.0   
3            6           80.0           9  ...          28.0         42.0   
4           13           61.0           6  ...          28.0         76.0   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0         30.0       1007.6       1008.7       NaN       2.0     21.0   
1         16.0       1017.6       1012.8       NaN       NaN     18.1   
2         19.0       1009.6       1008.2       1.0       NaN     18.1   
3          9.0       1008.9       1003.6       NaN       NaN     18.3   
4         93.0        994.3        993.0       8.0       8.0     17.4   

   Temp3pm  RainToday  
0     23.2          0  
1     26.5          0  
2     24.6          0  
3     30.2          0  
4     15.8          1  

[5 rows x 22 columns]

In [27]:
df['MinTemp'].isnull().sum()


np.int64(0)

In [28]:
df[['MaxTemp','Rainfall']]=df[['MaxTemp','Rainfall']].fillna(df[['MaxTemp','Rainfall']].median())

In [29]:
df[['Evaporation','Sunshine']]=df[['Evaporation','Sunshine']].fillna(df[['Evaporation','Sunshine']].median())

In [30]:
df[['WindGustSpeed','WindSpeed9am']]=df[['WindGustSpeed','WindSpeed9am']].fillna(df[['WindGustSpeed','WindSpeed9am']].median())

In [31]:
df[['WindSpeed3pm','Humidity9am']]=df[['WindSpeed3pm','Humidity9am']].fillna(df[['WindSpeed3pm','Humidity9am']].median())

In [32]:
df[['Humidity3pm','Pressure9am']]=df[['Humidity3pm','Pressure9am']].fillna(df[['Humidity3pm','Pressure9am']].median())

In [33]:
df[['Pressure3pm','Cloud9am']]=df[['Pressure3pm','Cloud9am']].fillna(df[['Pressure3pm','Cloud9am']].median())

In [34]:
df[['Cloud3pm','Temp9am']]=df[['Cloud3pm','Temp9am']].fillna(df[['Cloud3pm','Temp9am']].median())

In [35]:
df['Temp3pm']=df['Temp3pm'].fillna(df['Temp3pm'].median())

In [36]:
df['WindGustDir']=df['WindGustDir'].fillna(df['WindGustDir'].mode()[0])


In [37]:
df['WindDir9am']=df['WindDir9am'].fillna(df['WindDir9am'].mode()[0])

In [38]:
df['WindDir3pm']=df['WindDir3pm'].fillna(df['WindDir3pm'].mode()[0])

In [39]:
df['RainToday']=df['RainToday'].fillna(df['RainToday'].mode()[0])

In [40]:
df.isnull().sum()

row ID           0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
dtype: int64

In [41]:
x=df.drop(["RainToday"],axis=1)
y=df["RainToday"]
x

row ID  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0           0         2     12.9     25.7       0.0          4.8       8.5   
1           1         2      9.2     28.0       0.0          4.8       8.5   
2       10859         2     14.3     25.0       0.0          4.8       8.5   
3       21632         2      9.7     31.9       0.0          4.8       8.5   
4       32544         2     15.9     18.6      15.6          4.8       8.5   
...       ...       ...      ...      ...       ...          ...       ...   
42672   36506        41      2.4     19.1       0.0          4.8       8.5   
42673   36507        41      2.3     21.4       0.0          4.8       8.5   
42674   36508        41      2.6     22.5       0.0          4.8       8.5   
42675   36509        41      7.4     20.6       0.0          4.8       8.5   
42676   36510        41      7.8     27.0       0.0          4.8       8.5   

       WindGustDir  WindGustSpeed  WindDir9am  ...  WindSpeed9am  \
0               15           46.0          13  ...          19.0   
1                4           24.0           9  ...          11.0   
2               13           50.0          12  ...          20.0   
3                6           80.0           9  ...           7.0   
4               13           61.0           6  ...          28.0   
...            ...            ...         ...  ...           ...   
42672            0           33.0           9  ...          17.0   
42673            9           22.0           9  ...          11.0   
42674            8           19.0           8  ...           9.0   
42675            0           35.0           2  ...          15.0   
42676            9           28.0          10  ...          13.0   

       WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  \
0              26.0         38.0         30.0       1007.6       1008.7   
1               9.0         45.0         16.0       1017.6       1012.8   
2              24.0         49.0         19.0       1009.6       1008.2   
3              28.0         42.0          9.0       1008.9       1003.6   
4              28.0         76.0         93.0        994.3        993.0   
...             ...          ...          ...          ...          ...   
42672          17.0         59.0         24.0       1030.0       1026.2   
42673           7.0         60.0         28.0       1026.9       1022.8   
42674           7.0         59.0         24.0       1025.0       1021.4   
42675          17.0         63.0         33.0       1027.2       1023.3   
42676           7.0         51.0         24.0       1019.4       1016.5   

       Cloud9am  Cloud3pm  Temp9am  Temp3pm  
0           5.0       2.0     21.0     23.2  
1           5.0       5.0     18.1     26.5  
2           1.0       5.0     18.1     24.6  
3           5.0       5.0     18.3     30.2  
4           8.0       8.0     17.4     15.8  
...         ...       ...      ...      ...  
42672       5.0       5.0      8.0     18.8  
42673       5.0       5.0      8.9     20.3  
42674       5.0       5.0      8.8     22.1  
42675       5.0       5.0     11.0     20.3  
42676       3.0       2.0     15.1     26.0  

[42677 rows x 21 columns]

In [42]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X=sc.fit_transform(x)
print(X)

[[0.00000000e+00 4.16666667e-02 5.27500000e-01 ... 2.50000000e-01
  6.05150215e-01 5.62992126e-01]
 [2.34323742e-05 4.16666667e-02 4.35000000e-01 ... 6.25000000e-01
  5.42918455e-01 6.27952756e-01]
 [2.54452151e-01 4.16666667e-02 5.62500000e-01 ... 6.25000000e-01
  5.42918455e-01 5.90551181e-01]
 ...
 [8.55469116e-01 8.54166667e-01 2.70000000e-01 ... 6.25000000e-01
  3.43347639e-01 5.41338583e-01]
 [8.55492549e-01 8.54166667e-01 3.90000000e-01 ... 6.25000000e-01
  3.90557940e-01 5.05905512e-01]
 [8.55515981e-01 8.54166667e-01 4.00000000e-01 ... 2.50000000e-01
  4.78540773e-01 6.18110236e-01]]


In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42) #important library, (0.2-20% data for test), random atate = 42 takes 42 data 1st then nxet 42...
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(34141, 21)
(8536, 21)
(34141,)
(8536,)


In [44]:
from  sklearn.linear_model import LogisticRegression #for classification
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 0, 0, ..., 0, 0, 0])

In [45]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8881208997188379
[[6296  222    0]
 [ 656 1285    0]
 [  70    7    0]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93      6518
           1       0.85      0.66      0.74      1941
           2       0.00      0.00      0.00        77

    accuracy                           0.89      8536
   macro avg       0.58      0.54      0.56      8536
weighted avg       0.88      0.89      0.88      8536



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [46]:
from  sklearn.linear_model import LogisticRegression #for classification
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)
y_pred

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 0, 0, ..., 0, 0, 0])

In [47]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report  #r2_score,mean_squared_error,mean_absolute_error error formula  y-y^
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.884020618556701
[[6258  260    0]
 [ 653 1288    0]
 [  72    5    0]]
              precision    recall  f1-score   support

           0       0.90      0.96      0.93      6518
           1       0.83      0.66      0.74      1941
           2       0.00      0.00      0.00        77

    accuracy                           0.88      8536
   macro avg       0.58      0.54      0.55      8536
weighted avg       0.87      0.88      0.88      8536



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
